export { appRegistry, registerApp, createApp } from './app-registry'
export { getAppUrl, openExternalApp } from './app-urls'
export { DEFAULT_APPS } from './default-apps'
export { calculateWindowDimensions, getResponsiveSize, isMobileScreen, isDesktopScreen } from './window-positioning'
export { organizeIconsIntoGroups, isIconInGroup, findIconGroup } from './icon-groups'
