// ========================================
// MATÉRIAUX - PRIX DYNAMIQUE PAR PÉRIODE
// ========================================
// 
// REFACTORISATION: priceMultiplier statique → Dynamique par période
// Basé sur analyses historiques réelles et découvertes technologiques
//
// Chaque période (bronze-age, iron-age, medieval, renaissance, enlightenment, industrial, modern, contemporary, future-near, future-far)
// a des valeurs de prix différentes basées sur:
// - Disponibilité du matériau
// - Technicité d'extraction/production
// - Tournants technologiques (ex: Bessemer 1855, Hall-Héroult 1886)
// - Demande du marché (ex: lithium 2020+)

import type { Material } from './materials.types'

// ========================================
// MÉTAUX
// ========================================

export const IRON: Material = {
  id: 'iron',
  name: 'Fer',
  category: 'metal',
  density: 7.87,
  hardness: { type: 'mohs', value: 4 },
  mechanical: { tensileStrength: 250 },
  thermal: { thermalConductivity: 80, meltingPoint: 1538 },
  sharpnessScore: { overall: 6.8, edgeGeometry: { score: 0.8, radiusMicrometers: 2 }, toughness: 0.7 },
  sharpness: 'sharp',
  durability: 'medium',
  flexibility: 'rigid',
  // ✅ NOUVEAU: Prix dynamique par période (commence à iron-age, pas bronze-age!)
  priceMultiplier: {
    'iron-age': 5.0,           // Découverte ~1200 BCE
    'medieval': 4.0,
    'renaissance': 3.0,
    'enlightenment': 2.0,
    'industrial': 0.9,
    'modern': 0.7,
    'contemporary': 0.6,
    'future-near': 0.5,
    'future-far': 0.5,
  },
  weightFactor: 0.95,
  durabilityFactor: 0.7,
  effectivenessFactor: 0.85,
  historicalDiscovery: '1200 BCE',
  specialProperties: ['magnetic', 'abundant'],
  description: 'Métal commun, forgeable et trempable. Disponible depuis l\'Antiquité, baisse progressive 90% jusqu\'au futur.',
  cost: 120,
  rarity: 2,
}

export const STEEL: Material = {
  id: 'steel',
  name: 'Acier',
  category: 'metal',
  density: 7.85,
  hardness: { type: 'hrc', value: 52, range: [40, 65] },
  mechanical: { tensileStrength: 500, tensileStrengthRange: [400, 600] },
  thermal: { thermalConductivity: 50, meltingPoint: 1500 },
  sharpnessScore: { overall: 7.8, edgeGeometry: { score: 0.85, radiusMicrometers: 1.5 }, toughness: 0.75 },
  sharpness: 'very-sharp',
  durability: 'high',
  flexibility: 'rigid',
  // ✅ NOUVEAU: Bessemer 1855 = tournant majeur
  priceMultiplier: {
    'medieval': 8.5,
    'renaissance': 7.2,
    'enlightenment': 5.5,
    'industrial': 3.6,
    'modern': 1.8,
    'contemporary': 1.2,
    'future-near': 0.9,
    'future-far': 0.9,
  },
  weightFactor: 0.98,
  durabilityFactor: 0.8,
  effectivenessFactor: 0.9,
  historicalDiscovery: '500 BCE (ancienne), 1855 (Bessemer revolution)',
  specialProperties: ['magnetic'],
  description: 'Alliage fer + carbone. Révolution 1855: convertisseur Bessemer baisse prix 75%.',
  cost: 180,
  rarity: 2,
}

export const STAINLESS_STEEL: Material = {
  id: 'stainless_steel',
  name: 'Acier Inoxydable',
  category: 'metal',
  density: 8.0,
  hardness: { type: 'hrc', value: 35, range: [25, 45] },
  mechanical: { tensileStrength: 515, tensileStrengthRange: [515, 860] },
  thermal: { thermalConductivity: 16, meltingPoint: 1500 },
  sharpnessScore: { overall: 6.9, edgeGeometry: { score: 0.8, radiusMicrometers: 1.5 }, toughness: 0.7 },
  sharpness: 'sharp',
  durability: 'high',
  flexibility: 'rigid',
  // ✅ NOUVEAU: Découvert 1912, prix baisse 50% post-WWII
  priceMultiplier: {
    'modern': 5,
    'contemporary': 3.5,
    'future-near': 2.5,
    'future-far': 2.5,
  },
  weightFactor: 1.0,
  durabilityFactor: 0.9,
  effectivenessFactor: 0.85,
  historicalDiscovery: '1912 (Harry Brearley)',
  specialProperties: ['corrosion_resistant'],
  description: 'Acier + chrome. Découvert 1912, standard médical moderne. Baisse 50% modern→future.',
  cost: 250,
  rarity: 3,
}

export const BRONZE: Material = {
  id: 'bronze',
  name: 'Bronze',
  category: 'metal',
  density: 8.7,
  hardness: { type: 'mohs', value: 3 },
  mechanical: { tensileStrength: 350 },
  thermal: { thermalConductivity: 50, meltingPoint: 1000 },
  sharpnessScore: { overall: 6.2, edgeGeometry: { score: 0.75, radiusMicrometers: 2 }, toughness: 0.65 },
  sharpness: 'sharp',
  durability: 'medium',
  flexibility: 'rigid',
  // ✅ NOUVEAU: Révolution 3000 BCE, baisse 80% jusqu'au futur
  priceMultiplier: {
    'bronze-age': 4,
    'iron-age': 3.8,
    'medieval': 3.2,
    'renaissance': 2.5,
    'enlightenment': 2,
    'industrial': 1.3,
    'modern': 1,
    'contemporary': 0.9,
    'future-near': 0.8,
    'future-far': 0.8,
  },
  weightFactor: 0.85,
  durabilityFactor: 0.65,
  effectivenessFactor: 0.8,
  historicalDiscovery: '3000 BCE',
  specialProperties: ['corrosion_resistant'],
  description: 'Alliage cuivre + étain. Révolution Âge du Bronze 3000 BCE. Baisse 80% ancient→future.',
  cost: 150,
  rarity: 3,
}

export const COPPER: Material = {
  id: 'copper',
  name: 'Cuivre',
  category: 'metal',
  density: 8.96,
  hardness: { type: 'mohs', value: 2.5 },
  mechanical: { tensileStrength: 210 },
  thermal: { thermalConductivity: 398, meltingPoint: 1085 },
  sharpnessScore: { overall: 2.1, edgeGeometry: { score: 0.3, radiusMicrometers: 5 }, toughness: 0.4 },
  sharpness: 'blunt',
  durability: 'low',
  flexibility: 'flexible',
  // ✅ NOUVEAU: Utilisé 9000 BCE, baisse 80% avec pic contemporary (demande verte)
  priceMultiplier: {
    'bronze-age': 3.5,
    'iron-age': 3.3,
    'medieval': 2.8,
    'renaissance': 2.2,
    'enlightenment': 1.8,
    'industrial': 1.2,
    'modern': 0.8,
    'contemporary': 0.9,
    'future-near': 0.7,
    'future-far': 0.7,
  },
  weightFactor: 0.9,
  durabilityFactor: 0.4,
  effectivenessFactor: 0.3,
  historicalDiscovery: '9000 BCE',
  specialProperties: ['conductive'],
  description: 'Premier métal travaillé. Baisse 80% ancient→future. Pic contemporary (demande électrification).',
  cost: 100,
  rarity: 3,
}

export const TIN: Material = {
  id: 'tin',
  name: 'Étain',
  category: 'metal',
  density: 7.31,
  hardness: { type: 'mohs', value: 1.5 },
  mechanical: { tensileStrength: 170 },
  thermal: { thermalConductivity: 66, meltingPoint: 232 },
  sharpnessScore: { overall: 1.5, edgeGeometry: { score: 0.2, radiusMicrometers: 8 }, toughness: 0.3 },
  sharpness: 'blunt',
  durability: 'low',
  flexibility: 'flexible',
  // ✅ NOUVEAU: Révolutionnaire dans bronze 3000 BCE, peak contemporary
  priceMultiplier: {
    'bronze-age': 2.5,
    'iron-age': 2.4,
    'medieval': 1.8,
    'renaissance': 1.6,
    'enlightenment': 1.4,
    'industrial': 1,
    'modern': 0.9,
    'contemporary': 1.2,
    'future-near': 0.8,
    'future-far': 0.8,
  },
  weightFactor: 0.8,
  durabilityFactor: 0.35,
  effectivenessFactor: 0.5,
  historicalDiscovery: '5000 BCE',
  specialProperties: ['corrosion_resistant'],
  description: 'Mou seul, révolutionnaire comme composant du bronze. Étain reste modérément cher.',
  cost: 120,
  rarity: 4,
}

export const SILVER: Material = {
  id: 'silver',
  name: 'Argent',
  category: 'metal',
  density: 10.5,
  hardness: { type: 'mohs', value: 2.5 },
  mechanical: { tensileStrength: 160 },
  thermal: { thermalConductivity: 429, meltingPoint: 962 },
  sharpnessScore: { overall: 1.5, edgeGeometry: { score: 0.25, radiusMicrometers: 6 }, toughness: 0.3 },
  sharpness: 'blunt',
  durability: 'low',
  flexibility: 'flexible',
  // ✅ NOUVEAU: Précieux depuis 5000 BCE, stabilité ~70-90x toutes périodes
  priceMultiplier: {
    'bronze-age': 70,
    'iron-age': 66.5,
    'medieval': 72,
    'renaissance': 68,
    'enlightenment': 75,
    'industrial': 80,
    'modern': 85,
    'contemporary': 88,
    'future-near': 86,
    'future-far': 86,
  },
  weightFactor: 1.05,
  durabilityFactor: 0.35,
  effectivenessFactor: 0.5,
  historicalDiscovery: '5000 BCE',
  specialProperties: ['precious', 'conductive', 'antimicrobial'],
  description: 'Métal précieux. Stabilité relative ~70-90x. Variations ±10% selon époque.',
  cost: 400,
  rarity: 6,
}

export const GOLD: Material = {
  id: 'gold',
  name: 'Or',
  category: 'metal',
  density: 19.3,
  hardness: { type: 'mohs', value: 2.5 },
  mechanical: { tensileStrength: 100 },
  thermal: { thermalConductivity: 317, meltingPoint: 1064 },
  sharpnessScore: { overall: 1.2, edgeGeometry: { score: 0.2, radiusMicrometers: 8 }, toughness: 0.25 },
  sharpness: 'blunt',
  durability: 'very-low',
  flexibility: 'very-flexible',
  // ✅ NOUVEAU: Précieux 7000 BCE, valeur refuge très stable
  priceMultiplier: {
    'bronze-age': 60,
    'iron-age': 57,
    'medieval': 65,
    'renaissance': 62,
    'enlightenment': 68,
    'industrial': 72,
    'modern': 78,
    'contemporary': 85,
    'future-near': 82,
    'future-far': 82,
  },
  weightFactor: 1.9,
  durabilityFactor: 0.3,
  effectivenessFactor: 0.4,
  historicalDiscovery: '7000 BCE',
  specialProperties: ['precious', 'heavy', 'conductive'],
  description: 'Métal précieux très mou. Très haute stabilité ~60-85x. Valeur refuge constante.',
  cost: 500,
  rarity: 7,
}

export const PLATINUM: Material = {
  id: 'platinum',
  name: 'Platine',
  category: 'metal',
  density: 21.45,
  hardness: { type: 'mohs', value: 4.3 },
  mechanical: { tensileStrength: 125 },
  thermal: { thermalConductivity: 72, meltingPoint: 1769 },
  sharpnessScore: { overall: 3.2, edgeGeometry: { score: 0.4, radiusMicrometers: 6 }, toughness: 0.6 },
  sharpness: 'blunt',
  durability: 'medium',
  flexibility: 'rigid',
  // ✅ NOUVEAU: Rare, extraction très complexe, peu d'amélioration
  priceMultiplier: {
    'modern': 80,
    'contemporary': 78,
    'future-near': 75,
    'future-far': 75,
  },
  weightFactor: 2.1,
  durabilityFactor: 0.7,
  effectivenessFactor: 0.6,
  historicalDiscovery: '1791 (William Gregor)',
  specialProperties: ['precious', 'rare', 'heavy', 'corrosion_resistant'],
  description: 'Extrêmement rare et dense. Extraction très complexe = reste ~80x cher.',
  cost: 800,
  rarity: 9,
}

export const ALUMINUM: Material = {
  id: 'aluminum',
  name: 'Aluminium',
  category: 'metal',
  density: 2.7,
  hardness: { type: 'mohs', value: 2.75 },
  mechanical: { tensileStrength: 276 },
  thermal: { thermalConductivity: 167, meltingPoint: 660 },
  sharpnessScore: { overall: 3.0, edgeGeometry: { score: 0.35, radiusMicrometers: 6 }, toughness: 0.55 },
  sharpness: 'blunt',
  durability: 'low',
  flexibility: 'rigid',
  // ✅ NOUVEAU: Révolution Hall-Héroult 1886 = 80% baisse en 7 ans
  priceMultiplier: {
    'modern': 1,
    'contemporary': 0.8,
    'future-near': 0.7,
    'future-far': 0.7,
  },
  weightFactor: 0.27,
  durabilityFactor: 0.4,
  effectivenessFactor: 0.5,
  historicalDiscovery: '1886 (Hall-Héroult process)',
  specialProperties: ['light', 'abundant', 'corrosion_resistant', 'conductive'],
  description: 'Valait plus que l\'or en 1800. Révolution 1886 = 80% baisse en 7 ans.',
  cost: 100,
  rarity: 1,
}

export const TITANIUM: Material = {
  id: 'titanium',
  name: 'Titane',
  category: 'metal',
  density: 4.51,
  hardness: { type: 'mohs', value: 6 },
  mechanical: { tensileStrength: 434, elasticModulus: 103 },
  thermal: { thermalConductivity: 22, meltingPoint: 1668 },
  sharpnessScore: { overall: 7.1, edgeGeometry: { score: 0.85, radiusMicrometers: 2 }, toughness: 0.75 },
  sharpness: 'sharp',
  durability: 'high',
  flexibility: 'rigid',
  // ✅ NOUVEAU: Extraction très complexe (Kroll process), peu d'amélioration
  priceMultiplier: {
    'modern': 6,
    'contemporary': 5.8,
    'future-near': 5.2,
    'future-far': 5.2,
  },
  weightFactor: 0.45,
  durabilityFactor: 0.9,
  effectivenessFactor: 0.9,
  historicalDiscovery: '1791 (William Gregor)',
  specialProperties: ['light', 'corrosion_resistant', 'biocompatible'],
  description: 'Rapport résistance/poids inégalé. Extraction très complexe = reste ~6x cher 100+ ans.',
  cost: 300,
  rarity: 5,
}

export const TUNGSTEN: Material = {
  id: 'tungsten',
  name: 'Tungstène',
  category: 'metal',
  density: 19.25,
  hardness: { type: 'mohs', value: 7.5 },
  mechanical: { tensileStrength: 510 },
  thermal: { thermalConductivity: 173, meltingPoint: 3422 },
  sharpnessScore: { overall: 8.1, edgeGeometry: { score: 0.9, radiusMicrometers: 1 }, toughness: 0.8 },
  sharpness: 'very-sharp',
  durability: 'very-high',
  flexibility: 'rigid',
  // ✅ NOUVEAU: Rare, très lourd, point fusion extrême
  priceMultiplier: {
    'modern': 8,
    'contemporary': 7.8,
    'future-near': 7.5,
    'future-far': 7.5,
  },
  weightFactor: 1.9,
  durabilityFactor: 0.95,
  effectivenessFactor: 0.95,
  historicalDiscovery: '1783',
  specialProperties: ['heavy', 'rare', 'corrosion_resistant'],
  description: 'Point de fusion le plus élevé. Utilisé pour les balles perforantes.',
  cost: 400,
  rarity: 6,
}

// ========================================
// ORGANIQUES
// ========================================

export const WOOD: Material = {
  id: 'wood',
  name: 'Bois',
  category: 'organic',
  density: 0.6,
  hardness: { type: 'mohs', value: 2 },
  mechanical: { tensileStrength: 40 },
  thermal: { thermalConductivity: 0.15 },
  sharpnessScore: { overall: 4.5, edgeGeometry: { score: 0.5, radiusMicrometers: 10 }, toughness: 0.6 },
  sharpness: 'blunt',
  durability: 'medium',
  flexibility: 'flexible',
  // ✅ NOUVEAU: Ultra-abondant, baisse 80% ancient→future
  priceMultiplier: {
    'bronze-age': 0.5,
    'iron-age': 0.5,
    'medieval': 0.4,
    'renaissance': 0.35,
    'enlightenment': 0.3,
    'industrial': 0.2,
    'modern': 0.15,
    'contemporary': 0.12,
    'future-near': 0.1,
    'future-far': 0.1,
  },
  weightFactor: 0.3,
  durabilityFactor: 0.4,
  effectivenessFactor: 0.7,
  historicalDiscovery: 'Paléolithique',
  specialProperties: ['light', 'abundant', 'insulator'],
  description: 'Matériau naturel ultra-abondant. Ultra-banal toutes périodes, baisse 80% total.',
  cost: 20,
  rarity: 1,
}

export const LEATHER: Material = {
  id: 'leather',
  name: 'Cuir',
  category: 'organic',
  density: 0.95,
  hardness: { type: 'mohs', value: 1.5 },
  mechanical: { tensileStrength: 15 },
  thermal: { thermalConductivity: 0.15 },
  sharpnessScore: { overall: 2.0, edgeGeometry: { score: 0.3, radiusMicrometers: 15 }, toughness: 0.5 },
  durability: 'medium',
  flexibility: 'flexible',
  // ✅ NOUVEAU: 5000 BCE, baisse 80% ancient→future
  priceMultiplier: {
    'bronze-age': 2,
    'iron-age': 1.9,
    'medieval': 1.8,
    'renaissance': 1.5,
    'enlightenment': 1.2,
    'industrial': 0.8,
    'modern': 0.6,
    'contemporary': 0.5,
    'future-near': 0.4,
    'future-far': 0.4,
  },
  weightFactor: 0.4,
  durabilityFactor: 0.35,
  effectivenessFactor: 0.5,
  historicalDiscovery: '5000 BCE',
  specialProperties: ['flexible'],
  description: 'Peau tannée. Excellent armure légère. Baisse 80% ancient→future.',
  cost: 40,
  rarity: 2,
}

export const CLOTH: Material = {
  id: 'cloth',
  name: 'Tissu',
  category: 'organic',
  density: 0.2,
  hardness: { type: 'mohs', value: 1 },
  mechanical: { tensileStrength: 5 },
  thermal: { thermalConductivity: 0.1 },
  durability: 'low',
  flexibility: 'very-flexible',
  priceMultiplier: {
    'bronze-age': 0.3,
    'iron-age': 0.3,
    'medieval': 0.25,
    'renaissance': 0.2,
    'enlightenment': 0.18,
    'industrial': 0.12,
    'modern': 0.08,
    'contemporary': 0.06,
    'future-near': 0.05,
    'future-far': 0.05,
  },
  weightFactor: 0.15,
  durabilityFactor: 0.2,
  effectivenessFactor: 0.3,
  historicalDiscovery: '5000 BCE',
  specialProperties: ['light', 'flexible', 'insulator'],
  description: 'Textile tissé, léger et confortable.',
  cost: 15,
  rarity: 1,
}

export const BONE: Material = {
  id: 'bone',
  name: 'Os',
  category: 'organic',
  density: 1.8,
  hardness: { type: 'mohs', value: 2.5 },
  mechanical: { tensileStrength: 130 },
  thermal: { thermalConductivity: 0.5 },
  sharpnessScore: { overall: 6.8, edgeGeometry: { score: 0.75, radiusMicrometers: 2 }, toughness: 0.6 },
  sharpness: 'sharp',
  durability: 'medium',
  flexibility: 'rigid',
  // ✅ NOUVEAU: Paléolithique, remplacé progressivement par métal
  priceMultiplier: {
    'bronze-age': 1.5,
    'iron-age': 1.4,
    'medieval': 1.3,
    'renaissance': 1,
    'enlightenment': 0.7,
    'industrial': 0.4,
    'modern': 0.3,
    'contemporary': 0.25,
    'future-near': 0.2,
    'future-far': 0.2,
  },
  weightFactor: 0.7,
  durabilityFactor: 0.5,
  effectivenessFactor: 0.75,
  historicalDiscovery: 'Paléolithique',
  specialProperties: ['brittle'],
  description: 'Composite naturel. Peut être très tranchant. Remplacé progressivement.',
  cost: 25,
  rarity: 2,
}

export const HORN: Material = {
  id: 'horn',
  name: 'Corne',
  category: 'organic',
  density: 1.3,
  hardness: { type: 'mohs', value: 2 },
  mechanical: { tensileStrength: 60 },
  thermal: { thermalConductivity: 0.3 },
  sharpnessScore: { overall: 5.2, edgeGeometry: { score: 0.65, radiusMicrometers: 5 }, toughness: 0.7 },
  sharpness: 'sharp',
  durability: 'low',
  flexibility: 'flexible',
  // ✅ NOUVEAU: Antiquité, remplacé progressivement
  priceMultiplier: {
    'bronze-age': 1.2,
    'iron-age': 1.1,
    'medieval': 1,
    'renaissance': 0.8,
    'enlightenment': 0.6,
    'industrial': 0.4,
    'modern': 0.3,
    'contemporary': 0.25,
    'future-near': 0.2,
    'future-far': 0.2,
  },
  weightFactor: 0.5,
  durabilityFactor: 0.45,
  effectivenessFactor: 0.65,
  historicalDiscovery: 'Antiquité',
  specialProperties: ['flexible', 'light'],
  description: 'Matériau flexible et résilient. Excellent pour les arcs.',
  cost: 30,
  rarity: 2,
}

export const FUR: Material = {
  id: 'fur',
  name: 'Fourrure',
  category: 'organic',
  density: 0.3,
  hardness: { type: 'mohs', value: 1 },
  mechanical: { tensileStrength: 8 },
  thermal: { thermalConductivity: 0.05 },
  durability: 'low',
  flexibility: 'very-flexible',
  priceMultiplier: {
    'bronze-age': 0.8,
    'iron-age': 0.8,
    'medieval': 0.7,
    'renaissance': 0.6,
    'enlightenment': 0.5,
    'industrial': 0.3,
    'modern': 0.25,
    'contemporary': 0.2,
    'future-near': 0.15,
    'future-far': 0.15,
  },
  weightFactor: 0.2,
  durabilityFactor: 0.25,
  effectivenessFactor: 0.4,
  historicalDiscovery: 'Paléolithique',
  specialProperties: ['light', 'flexible', 'insulator'],
  description: 'Peau avec poils. Chaude et isolante.',
  cost: 35,
  rarity: 2,
}

// ========================================
// MINÉRAUX
// ========================================

export const FLINT: Material = {
  id: 'flint',
  name: 'Silex',
  category: 'mineral',
  density: 2.64,
  hardness: { type: 'mohs', value: 7 },
  mechanical: { tensileStrength: 60 },
  thermal: { thermalConductivity: 3.5 },
  sharpnessScore: { overall: 7.2, edgeGeometry: { score: 0.85, radiusMicrometers: 1.5 }, toughness: 0.65 },
  sharpness: 'sharp',
  durability: 'medium',
  flexibility: 'rigid',
  // ✅ NOUVEAU: Paléolithique, abondant, baisse 94%
  priceMultiplier: {
    'bronze-age': 0.8,
    'iron-age': 0.8,
    'medieval': 0.5,
    'renaissance': 0.3,
    'enlightenment': 0.2,
    'industrial': 0.1,
    'modern': 0.07,
    'contemporary': 0.06,
    'future-near': 0.05,
    'future-far': 0.05,
  },
  weightFactor: 1.05,
  durabilityFactor: 0.85,
  effectivenessFactor: 0.7,
  historicalDiscovery: 'Paléolithique (-2.5M années)',
  specialProperties: ['fireproof', 'ultra_sharp', 'abundant', 'brittle'],
  description: 'Produit des étincelles. Révolutionnaire pour l\'allumage du feu.',
  cost: 15,
  rarity: 2,
}

export const STONE: Material = {
  id: 'stone',
  name: 'Pierre',
  category: 'mineral',
  density: 2.5,
  hardness: { type: 'mohs', value: 4 },
  mechanical: { tensileStrength: 10 },
  thermal: { thermalConductivity: 2.5 },
  sharpnessScore: { overall: 4.5, edgeGeometry: { score: 0.5, radiusMicrometers: 8 }, toughness: 0.7 },
  sharpness: 'blunt',
  durability: 'high',
  flexibility: 'rigid',
  // ✅ NOUVEAU: Ultra-cheap, 85% baisse
  priceMultiplier: {
    'bronze-age': 0.3,
    'iron-age': 0.3,
    'medieval': 0.2,
    'renaissance': 0.15,
    'enlightenment': 0.12,
    'industrial': 0.08,
    'modern': 0.06,
    'contemporary': 0.05,
    'future-near': 0.04,
    'future-far': 0.04,
  },
  weightFactor: 1.0,
  durabilityFactor: 0.8,
  effectivenessFactor: 0.6,
  historicalDiscovery: 'Paléolithique (-2.5M années)',
  specialProperties: ['heavy', 'abundant', 'brittle'],
  description: 'Premier matériau utilisé par l\'humanité. Ultra-cheap toutes périodes.',
  cost: 10,
  rarity: 1,
}

export const OBSIDIAN: Material = {
  id: 'obsidian',
  name: 'Obsidienne',
  category: 'mineral',
  density: 2.35,
  hardness: { type: 'mohs', value: 5.5 },
  mechanical: { tensileStrength: 50 },
  thermal: { thermalConductivity: 1.3 },
  sharpnessScore: { overall: 9.2, edgeGeometry: { score: 0.95, radiusMicrometers: 0.5 }, toughness: 0.4 },
  sharpness: 'very-sharp',
  durability: 'low',
  flexibility: 'rigid',
  // ✅ NOUVEAU: Paléolithique, tranchant exceptenel mais brittle
  priceMultiplier: {
    'bronze-age': 2,
    'iron-age': 1.9,
    'medieval': 1.5,
    'renaissance': 1,
    'enlightenment': 0.7,
    'industrial': 0.4,
    'modern': 0.3,
    'contemporary': 0.25,
    'future-near': 0.2,
    'future-far': 0.2,
  },
  weightFactor: 0.95,
  durabilityFactor: 0.6,
  effectivenessFactor: 0.95,
  historicalDiscovery: 'Paléolithique',
  specialProperties: ['ultra_sharp', 'fragile', 'brittle'],
  description: 'Verre volcanique. 500x plus tranchant que l\'acier chirurgical.',
  cost: 50,
  rarity: 4,
}

export const GRANITE: Material = {
  id: 'granite',
  name: 'Granit',
  category: 'mineral',
  density: 2.75,
  hardness: { type: 'mohs', value: 6 },
  mechanical: { tensileStrength: 15 },
  thermal: { thermalConductivity: 3.0, meltingPoint: 1260 },
  sharpnessScore: { overall: 3.0, edgeGeometry: { score: 0.4, radiusMicrometers: 10 }, toughness: 0.8 },
  sharpness: 'blunt',
  durability: 'high',
  flexibility: 'rigid',
  // ✅ NOUVEAU: Antique, très résistant, abondant, baisse 87%
  priceMultiplier: {
    'bronze-age': 1.2,
    'iron-age': 1.1,
    'medieval': 0.9,
    'renaissance': 0.7,
    'enlightenment': 0.6,
    'industrial': 0.4,
    'modern': 0.25,
    'contemporary': 0.2,
    'future-near': 0.15,
    'future-far': 0.15,
  },
  weightFactor: 1.1,
  durabilityFactor: 0.9,
  effectivenessFactor: 0.5,
  historicalDiscovery: 'Antiquité',
  specialProperties: ['heavy', 'abundant'],
  description: 'Roche ignée très résistante. Utilisée pour les pyramides et monuments.',
  cost: 20,
  rarity: 1,
}

export const MARBLE: Material = {
  id: 'marble',
  name: 'Marbre',
  category: 'mineral',
  density: 2.71,
  hardness: { type: 'mohs', value: 3 },
  mechanical: { tensileStrength: 8 },
  thermal: { thermalConductivity: 2.8, meltingPoint: 900 },
  sharpnessScore: { overall: 2.1, edgeGeometry: { score: 0.3, radiusMicrometers: 15 }, toughness: 0.5 },
  sharpness: 'blunt',
  durability: 'medium',
  flexibility: 'rigid',
  // ✅ NOUVEAU: Luxe symbole, baisse 80%
  priceMultiplier: {
    'bronze-age': 2,
    'iron-age': 1.9,
    'medieval': 1.8,
    'renaissance': 1.5,
    'enlightenment': 1.2,
    'industrial': 0.8,
    'modern': 0.6,
    'contemporary': 0.5,
    'future-near': 0.4,
    'future-far': 0.4,
  },
  weightFactor: 1.08,
  durabilityFactor: 0.6,
  effectivenessFactor: 0.4,
  historicalDiscovery: 'Antiquité',
  specialProperties: ['precious'],
  description: 'Cristal calcaire blanc prisé depuis l\'Antiquité.',
  cost: 80,
  rarity: 3,
}

export const DIAMOND: Material = {
  id: 'diamond',
  name: 'Diamant',
  category: 'mineral',
  density: 3.52,
  hardness: { type: 'mohs', value: 10 },
  mechanical: { tensileStrength: 2000 },
  thermal: { thermalConductivity: 2000, meltingPoint: 3823 },
  sharpnessScore: { overall: 8.5, edgeGeometry: { score: 0.9, radiusMicrometers: 0.5 }, toughness: 0.75 },
  sharpness: 'very-sharp',
  durability: 'very-high',
  flexibility: 'rigid',
  // ✅ NOUVEAU: Extraction tardiive (~1900s), baisse 30%
  priceMultiplier: {
    'modern': 10,
    'contemporary': 8.5,
    'future-near': 7,
    'future-far': 7,
  },
  weightFactor: 1.4,
  durabilityFactor: 1.0,
  effectivenessFactor: 0.95,
  historicalDiscovery: 'Antiquité (utilisé industriellement depuis 1900s)',
  specialProperties: ['rare', 'precious', 'transparent'],
  description: 'Matériau le plus dur connu. Conducteur thermique exceptionnel.',
  cost: 1000,
  rarity: 9,
}

export const CRYSTAL: Material = {
  id: 'crystal',
  name: 'Cristal',
  category: 'mineral',
  density: 2.6,
  hardness: { type: 'mohs', value: 7 },
  mechanical: { tensileStrength: 100 },
  thermal: { thermalConductivity: 10 },
  sharpnessScore: { overall: 6.5, edgeGeometry: { score: 0.75, radiusMicrometers: 3 }, toughness: 0.5 },
  sharpness: 'sharp',
  durability: 'low',
  flexibility: 'rigid',
  // ✅ NOUVEAU: Rareté modérée, baisse 66%
  priceMultiplier: {
    'bronze-age': 3,
    'iron-age': 2.8,
    'medieval': 2.8,
    'renaissance': 2.5,
    'enlightenment': 2.2,
    'industrial': 1.8,
    'modern': 1.5,
    'contemporary': 1.2,
    'future-near': 1,
    'future-far': 1,
  },
  weightFactor: 1.0,
  durabilityFactor: 0.55,
  effectivenessFactor: 0.7,
  historicalDiscovery: 'Antiquité',
  specialProperties: ['transparent', 'brittle', 'precious'],
  description: 'Minéral transparent et précieux.',
  cost: 200,
  rarity: 5,
}

export const GLASS: Material = {
  id: 'glass',
  name: 'Verre',
  category: 'mineral',
  density: 2.5,
  hardness: { type: 'mohs', value: 5.5 },
  mechanical: { tensileStrength: 60 },
  thermal: { thermalConductivity: 1.0, meltingPoint: 1700 },
  sharpnessScore: { overall: 5.4, edgeGeometry: { score: 0.65, radiusMicrometers: 4 }, toughness: 0.3 },
  durability: 'very-low',
  flexibility: 'rigid',
  // ✅ NOUVEAU: Medieval+ (1500 BCE production), baisse 90%
  priceMultiplier: {
    'medieval': 2,
    'renaissance': 1.5,
    'enlightenment': 1,
    'industrial': 0.5,
    'modern': 0.3,
    'contemporary': 0.25,
    'future-near': 0.2,
    'future-far': 0.2,
  },
  weightFactor: 1.0,
  durabilityFactor: 0.3,
  effectivenessFactor: 0.4,
  historicalDiscovery: '1500 BCE',
  specialProperties: ['transparent', 'brittle', 'fragile', 'insulator'],
  description: 'Transparent et cassant. Isolant thermique et électrique.',
  cost: 80,
  rarity: 2,
}

// ========================================
// COMPOSITES ET AUTRES
// ========================================

export const CERAMIC: Material = {
  id: 'ceramic',
  name: 'Céramique',
  category: 'composite',
  density: 2.3,
  hardness: { type: 'mohs', value: 5 },
  mechanical: { tensileStrength: 100 },
  thermal: { thermalConductivity: 1.5, meltingPoint: 1600 },
  sharpnessScore: { overall: 4.2, edgeGeometry: { score: 0.5, radiusMicrometers: 8 }, toughness: 0.6 },
  durability: 'medium',
  flexibility: 'rigid',
  // ✅ NOUVEAU: 9000 BCE, baisse 90%
  priceMultiplier: {
    'bronze-age': 1,
    'iron-age': 1,
    'medieval': 0.8,
    'renaissance': 0.6,
    'enlightenment': 0.5,
    'industrial': 0.3,
    'modern': 0.2,
    'contemporary': 0.15,
    'future-near': 0.1,
    'future-far': 0.1,
  },
  weightFactor: 0.92,
  durabilityFactor: 0.5,
  effectivenessFactor: 0.4,
  historicalDiscovery: '9000 BCE',
  specialProperties: ['brittle', 'insulator'],
  description: 'Argile cuite. Résistante à la chaleur.',
  cost: 70,
  rarity: 1,
}

export const ROPE: Material = {
  id: 'rope',
  name: 'Corde',
  category: 'organic',
  density: 0.4,
  hardness: { type: 'mohs', value: 1.5 },
  mechanical: { tensileStrength: 20 },
  thermal: { thermalConductivity: 0.2 },
  durability: 'medium',
  flexibility: 'very-flexible',
  priceMultiplier: {
    'bronze-age': 0.2,
    'iron-age': 0.2,
    'medieval': 0.18,
    'renaissance': 0.15,
    'enlightenment': 0.12,
    'industrial': 0.1,
    'modern': 0.08,
    'contemporary': 0.07,
    'future-near': 0.05,
    'future-far': 0.05,
  },
  weightFactor: 0.25,
  durabilityFactor: 0.45,
  effectivenessFactor: 0.5,
  historicalDiscovery: 'Paléolithique',
  specialProperties: ['flexible', 'light'],
  description: 'Fibres tressées, flexible et résistante.',
  cost: 25,
  rarity: 1,
}

export const CONCRETE: Material = {
  id: 'concrete',
  name: 'Béton',
  category: 'composite',
  density: 2.4,
  hardness: { type: 'mohs', value: 3.5 },
  mechanical: { tensileStrength: 4, tensileStrengthRange: [3, 5] },
  thermal: { thermalConductivity: 1.4 },
  sharpnessScore: { overall: 0.5, edgeGeometry: { score: 0.1, radiusMicrometers: 50 }, toughness: 0.7 },
  sharpness: 'blunt',
  durability: 'medium',
  flexibility: 'rigid',
  // ✅ NOUVEAU: Découvert 1824, ultra-cheap post-révolution
  priceMultiplier: {
    'modern': 0.5,
    'contemporary': 0.3,
    'future-near': 0.2,
    'future-far': 0.2,
  },
  weightFactor: 1.2,
  durabilityFactor: 0.7,
  effectivenessFactor: 0.3,
  historicalDiscovery: '1824 (Portland cement)',
  specialProperties: ['heavy', 'abundant'],
  description: 'Composite ciment + granulats. Excellent en compression.',
  cost: 50,
  rarity: 1,
}

export const PLASTIC: Material = {
  id: 'plastic',
  name: 'Plastique',
  category: 'composite',
  density: 0.9,
  hardness: { type: 'mohs', value: 2 },
  mechanical: { tensileStrength: 50 },
  thermal: { thermalConductivity: 0.25, meltingPoint: 200 },
  sharpnessScore: { overall: 2.0, edgeGeometry: { score: 0.3, radiusMicrometers: 10 }, toughness: 0.5 },
  sharpness: 'blunt',
  durability: 'low',
  flexibility: 'flexible',
  // ✅ NOUVEAU: 1920s polymères, révolution XXe
  priceMultiplier: {
    'contemporary': 0.3,
    'future-near': 0.2,
    'future-far': 0.2,
  },
  weightFactor: 0.09,
  durabilityFactor: 0.4,
  effectivenessFactor: 0.5,
  historicalDiscovery: '1920s (polymères synthétiques)',
  specialProperties: ['light', 'abundant', 'insulator'],
  description: 'Léger et bon marché. Révolution du XXe siècle.',
  cost: 30,
  rarity: 1,
}

export const CARBON_FIBER: Material = {
  id: 'carbon_fiber',
  name: 'Fibre de Carbone',
  category: 'composite',
  density: 1.6,
  hardness: { type: 'mohs', value: 7 },
  mechanical: { tensileStrength: 3500, elasticModulus: 230 },
  thermal: { thermalConductivity: 150, meltingPoint: 3000 },
  sharpnessScore: { overall: 8.0, edgeGeometry: { score: 0.9, radiusMicrometers: 1 }, toughness: 0.75 },
  sharpness: 'very-sharp',
  durability: 'high',
  flexibility: 'rigid',
  // ✅ NOUVEAU: 1960s (ex-PAN), reste chère, énergivore
  priceMultiplier: {
    'contemporary': 8,
    'future-near': 5,
    'future-far': 5,
  },
  weightFactor: 0.16,
  durabilityFactor: 0.9,
  effectivenessFactor: 0.85,
  historicalDiscovery: '1960s',
  specialProperties: ['light', 'conductive', 'rare'],
  description: 'Rapport résistance/poids exceptionnel. Utilisation militaire et sport élite.',
  cost: 400,
  rarity: 6,
}

export const GRAPHENE: Material = {
  id: 'graphene',
  name: 'Graphène',
  category: 'composite',
  density: 0.77,
  hardness: { type: 'mohs', value: 7 },
  mechanical: { tensileStrength: 130000, elasticModulus: 1000 },
  thermal: { thermalConductivity: 5000 },
  sharpnessScore: { overall: 9.5, edgeGeometry: { score: 0.98, radiusMicrometers: 0.1 }, toughness: 0.9 },
  sharpness: 'very-sharp',
  durability: 'very-high',
  flexibility: 'rigid',
  // ✅ NOUVEAU: Découvert 2004, ultra-théorique, très cher
  priceMultiplier: {
    'future-near': 100,
    'future-far': 100,
  },
  weightFactor: 0.08,
  durabilityFactor: 1.0,
  effectivenessFactor: 1.0,
  historicalDiscovery: '2004 (Geim & Novoselov)',
  specialProperties: ['light', 'conductive', 'experimental', 'theoretical', 'rare'],
  description: 'Matériau théorique. Propriétés quasi-impossibles en réalité.',
  cost: 1000,
  rarity: 10,
}

export const AEROGEL: Material = {
  id: 'aerogel',
  name: 'Aérogel',
  category: 'composite',
  density: 0.001,
  hardness: { type: 'mohs', value: 2 },
  mechanical: { tensileStrength: 5 },
  thermal: { thermalConductivity: 0.013, meltingPoint: 1500 },
  sharpnessScore: { overall: 1.5, edgeGeometry: { score: 0.2, radiusMicrometers: 20 }, toughness: 0.1 },
  sharpness: 'blunt',
  durability: 'very-low',
  flexibility: 'rigid',
  // ✅ NOUVEAU: 1931 (Kistler), ultra-expérimental
  priceMultiplier: {
    'future-near': 50,
    'future-far': 50,
  },
  weightFactor: 0.0001,
  durabilityFactor: 0.2,
  effectivenessFactor: 0.3,
  historicalDiscovery: '1931 (Kistler)',
  specialProperties: ['light', 'fragile', 'insulator', 'experimental', 'rare'],
  description: 'Matériau le plus léger connu. 99.8% air. Utilisé par la NASA.',
  cost: 500,
  rarity: 8,
}

/**
 * Tous les matériaux
 */
export const MATERIALS = {
  // Métaux primitifs
  COPPER,
  TIN,
  // Alliages
  BRONZE,
  IRON,
  STEEL,
  STAINLESS_STEEL,
  // Métaux précieux
  SILVER,
  GOLD,
  PLATINUM,
  // Métaux modernes
  ALUMINUM,
  TITANIUM,
  TUNGSTEN,
  // Organiques
  WOOD,
  LEATHER,
  CLOTH,
  BONE,
  HORN,
  FUR,
  // Minéraux
  FLINT,
  STONE,
  OBSIDIAN,
  GRANITE,
  MARBLE,
  DIAMOND,
  CRYSTAL,
  GLASS,
  // Composites
  CERAMIC,
  ROPE,
  CONCRETE,
  PLASTIC,
  CARBON_FIBER,
  GRAPHENE,
  AEROGEL,
} as const
